### ISSUE TITLE
Switch on or off all devices at the same time (group function)

### ISSUE THREAD

**Issue by juhnhooo** [fcrespel/chacondio10#1]
Hi

I see on on file send.cpp at line 57-58 that you don't use via argument the group... I use rtl_433 to capture or see the signal of remote controller and when I use the last button It switches on or off all of devices. This button use the argument group value 1, the rest of buttons use group value 0.

So if I want to switch on or switch off all devices at the same time I need to send group value 1.

Can you help me to edit send.cpp to enable group as argument?

Thanks for all.

**Comment by fcrespel** [comment]
Hello @juhnhooo, I haven't tested myself how the group feature works, do you have a sample signal to share? I'm curious which value is sent for the button number in that case (i.e. does it matter at all ..?)

Depending on your answer I will update the program with a new argument or with a specific value for the button (e.g. "-1").

**Comment by juhnhooo** [comment]
Hi
First of all thanks for all.
I try to share the collected data.
When I push the buttons then with my Flipper Zero I see this:
COMMAND - CAPTURE HEX WITH Flipper Zero (this part works well)
./send.sh 0 36712462 0 0	- 8C0C0380_SWITCH1 OFF
./send.sh 0 36712462 0 1 - 8C0C0390_SWITCH1 ON 
./send.sh 0 36712462 1 0 - 8C0C0381_SWITCH2 OFF
./send.sh 0 36712462 1 1 - 8C0C0391_SWITCH2 ON
./send.sh 0 36712462 2 0 - 8C0C0382_SWITCH3 OFF
./send.sh 0 36712462 2 1 - 8C0C0392_SWITCH3 ON

When I capture the signals with rtl_433 I see this:
CODIGO 		UNIT	GROUP 	STATE		HEX (FLIPPER ZERO)
36712462 	3 		0 		OFF/ON		8C0C0380_OFF 8C0C0390_ON (this part works well)
36712462 	2 		0 		OFF/ON		8C0C0381_OFF 8C0C0391_ON (this part works well)
36712462 	1		0		OFF/ON		8C0C0382_OFF 8C0C0392_ON (this part works well)
36712462 	3		1		OFF/ON		8C0C03B0_OFF 8C0C03A0_ON (this part I can't send with command)

I supose that if I can send the group I can send this 8C0C03B0_OFF 8C0C03A0_ON

Thanks another time.

**Comment by fcrespel** [comment]
Thanks for the feedback @juhnhooo. I just updated the code to allow using "-1" for the button number, which will trigger the group function. I successfully tested it on my own devices, please let me know if this works for you :-)

**Comment by juhnhooo** [comment]
Thanks a lot, 

I download and compiled the new code and works well.

Another time thanks a lot.
